[build]
	command = "gem install bundler && bundle install && npm run build" # Tell Netlify what command to use to build the site
	publish = "_site" # Tell Netlify where the publishable build resides
	environment = { NODE_VERSION = "18.12.1" }

[build.processing.html]
	pretty_urls = false
